apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.6
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "ps_db"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_USER
              value: "ps_user"
            - name: DB_PASSWORD
              value: "SecurePassword"
            # - name: KC_HTTP_RELATIVE_PATH
            #   value: "/auth/"
            # - name: KEYCLOAK_IMPORT
            #   value: "/opt/keycloak/import/realm-export.json"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: "realm-file"
              mountPath: "/opt/keycloak/data/import"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      volumes:
        - name: "realm-file"
          configMap:
            name: keycloak-init-configmap
            items:
            - key: realm-export.json
              path: realm-export.json 
  
          # hostPath:
          #   path: /Users/developer/pet/kraken-k8s/grogu-helm/realm-export.json
          #   type: FileOrCreate  