apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: auth.test
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.auth.name }}-clusterip
                port:
                  number: {{ .Values.auth.servicePort }}
    - host: grogu.test
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: krakend-service
                port:
                  number: 8000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.front.name }}-clusterip
                port:
                  number: {{ .Values.front.servicePort }}