apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
  # namespace: app-namespace
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: mmko67/k8s-krakend:0.0.5
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]