apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"