apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-service-config
  # namespace: casper-prod
  labels:
    app: redis-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  # namespace: casper-prod
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis-service
          image: redis:4.0.11-alpine
          args: ['/usr/local/etc/redis/redis.conf']
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              readOnly: true
              subPath: redis.conf
            - name: redis-persistent-storage
              mountPath: /data/redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: '1000m'
              memory: '2000Mi'
            requests:
              cpu: '1000m'
              memory: '2000Mi'
      volumes:
        - name: config
          configMap:
            defaultMode: 0666
            name: redis-service-config
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  # namespace: casper-prod
  labels:
    app: redis-service
spec:
  selector:
    app: redis-service
  ports:
    - name: redis-service
      port: 6379