apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}-clusterip
  # namespace: app-namespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.front.servicePort }}
    targetPort: {{ .Values.front.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.front.components }}
