apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.back.name }}-deployment
  # namespace: app-namespace
spec:
  selector:
    matchLabels:
      app: {{ .Values.back.components }}
  replicas: {{ .Values.back.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.back.components }}
    spec:
      containers:
      - name: {{ .Values.back.name }}
        image: "{{ .Values.back.image }}:{{ .Values.back.version }}"
        ports:
        - containerPort: {{ .Values.back.containerPort }}
        resources:
          limits: {{ .Values.back.limits | toYaml | nindent 14 }}
        envFrom:
            - secretRef:
                name: postgres-secret2
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.back.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 3
        # imagePullPolicy: Never
