apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}-clusterip
  # namespace: app-namespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.back.servicePort }}
    targetPort: {{ .Values.back.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.back.components }}
