apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  # namespace: app-namespace
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend
