apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret2
type: Opaque
data:
  # ps_db
  POSTGRES_DB: cHNfZGIK
  # ps_user
  POSTGRES_USER: cHNfdXNlcgo=
  # SecurePassword
  POSTGRES_PASSWORD: U2VjdXJlUGFzc3dvcmQK
  # "5432"
  POSTGRES_PORT: NTQzMgo=
  # POSTGRES_HOST: postgres
  # REDIS_HOST: redis-service
  # REDIS_PORT: "6379"